"""
Django settings for kaoyan_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils import timezone
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i2!($#7kx6g)ugfyr193@v!3l6*d(95v+yj38w0l$8&ycw$yga'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["49.234.26.95", "localhost", "127.0.0.1", "cm.whatsyourname.top", "whatsyourname.top"]

# HTTPS 反向代理：让 Django 识别 Nginx 传递的 SSL 头
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 信任的 CSRF 来源（通过域名访问时必须配置，否则 POST 请求会被拒绝）
CSRF_TRUSTED_ORIGINS = [
    "https://cm.whatsyourname.top",
    "http://cm.whatsyourname.top",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kaoyan_app',
    'zu_juan',
    'user',
    'ai_test',  # 新增 AI 出题模块
    'res_center',  # 资源中心
    'community',  # 社区讨论
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kaoyan_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kaoyan_project.vip_utils.vip_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'kaoyan_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
            'init_command': '',  # placeholder，实际通过 PRAGMA 设置
        }
    }
}

# SQLite 并发优化：启用 WAL 模式 + 增大 busy_timeout
# WAL 模式允许读写并发，解决 Django + Celery 同时访问时的 I/O 锁冲突
def _set_sqlite_wal(sender, connection, **kwargs):
    """数据库连接建立时自动开启 WAL 模式"""
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA busy_timeout=30000;')
        cursor.execute('PRAGMA synchronous=NORMAL;')

from django.db.backends.signals import connection_created
connection_created.connect(_set_sqlite_wal)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Session & CSRF Cookie — 避免同一域名下多个 Django 项目 cookie 冲突
SESSION_COOKIE_NAME = "kaoyan_sessionid"
CSRF_COOKIE_NAME = "kaoyan_csrftoken"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 登录跳转 URL（未登录用户访问需认证页面时自动重定向）
LOGIN_URL = '/login/'

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 自定义用户模型
AUTH_USER_MODEL = 'user.User'


APPLICATION_IDENTITY = "sk-e1a059c5a2e2471ab11ee30f2d0a19f1"
LLM_API_URL = "https://api.deepseek.com/chat/completions"  # 官方标准API地址
LLM_MODEL_NAME = "deepseek-chat"

# ==========================================
# Celery & Redis 异步任务配置
# ==========================================
# 消息代理（Broker），Celery 靠它来接收和发送任务
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/3'

# 接受的内容类型
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# ==========================================
# 邮件发送配置（邮箱验证用）
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '1285021260@qq.com'
EMAIL_HOST_PASSWORD = 'pwfkduhgjwonhihj'
DEFAULT_FROM_EMAIL = '厘米考研 <1285021260@qq.com>'

# 站点基本信息
SITE_NAME = "厘米考研"
SITE_TAGLINE = "你离上岸只差这一厘米，我们帮你！"
