# Generated by Django 6.0.3 on 2026-03-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='题型名称')),
            ],
            options={
                'verbose_name': '题型',
                'verbose_name_plural': '题型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('difficulty', models.CharField(choices=[('易', '易'), ('中', '中'), ('难', '难')], max_length=2, verbose_name='难度')),
                ('knowledge_point', models.CharField(max_length=200, verbose_name='知识点')),
                ('content', models.TextField(help_text='支持 Markdown + LaTeX 公式（$...$ / $$...$$）', verbose_name='题干')),
                ('options', models.JSONField(blank=True, help_text='选择题必填，JSON 数组格式，如 ["A. xxx","B. xxx","C. xxx","D. xxx"]', null=True, verbose_name='选项')),
                ('answer', models.TextField(help_text='支持 Markdown + LaTeX 公式', verbose_name='答案')),
                ('image', models.URLField(blank=True, null=True, verbose_name='插图URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.questiontype', verbose_name='题型')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-year', 'school', 'question_type'],
            },
        ),
    ]
