# Generated by Django 6.0.3 on 2026-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoyan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/', verbose_name='插图'),
        ),
    ]
