# Generated by Django 6.0.3 on 2026-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoyan_app', '0002_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='选择题填写正确选项字母，如 A、B、C、D', max_length=10, null=True, verbose_name='正确选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(help_text='支持 Markdown + LaTeX 公式，填空/简答等非选择题填写具体答案', verbose_name='答案解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='选择题必填，JSON 对象格式，如 {"A": "内容", "B": "内容"}', null=True, verbose_name='选项'),
        ),
    ]
