# Generated by Django 6.0.3 on 2026-03-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoyan_app', '0003_question_correct_answer_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='选择题填 A/B/C/D，判断题填 对/错，填空题多个空用分号隔开，解答题填参考答案要点，绘图题可留空', null=True, verbose_name='正确答案'),
        ),
    ]
