# Generated by Django 6.0.3 on 2026-03-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoyan_app', '0004_alter_question_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='专业课名称')),
            ],
            options={
                'verbose_name': '专业课',
                'verbose_name_plural': '专业课',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.subject', verbose_name='专业课'),
        ),
    ]
