# Generated by Django 6.0.3 on 2026-03-27 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaoyan_app', '0004_alter_question_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('preview', '预览中'), ('taking', '作答中'), ('submitted', '已提交')], default='preview', max_length=10, verbose_name='状态')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='作答时长(秒)')),
                ('score', models.IntegerField(default=0, verbose_name='客观题得分')),
                ('total_objective_score', models.IntegerField(default=0, verbose_name='客观题总分')),
                ('choice_count', models.IntegerField(default=0, verbose_name='选择题数量')),
                ('fill_count', models.IntegerField(default=0, verbose_name='填空题数量')),
                ('judge_count', models.IntegerField(default=0, verbose_name='判断题数量')),
                ('short_count', models.IntegerField(default=0, verbose_name='简答题数量')),
                ('calc_count', models.IntegerField(default=0, verbose_name='计算题数量')),
                ('draw_count', models.IntegerField(default=0, verbose_name='画图题数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='题目顺序')),
                ('user_answer', models.TextField(blank=True, null=True, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='zu_juan.exam', verbose_name='试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_count', models.IntegerField(default=1, verbose_name='错误次数')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='最近错误时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题本',
                'ordering': ['-last_wrong_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
