# Generated by Django 6.0.3 on 2026-03-27 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaoyan_app', '0004_alter_question_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='生成状态')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='异步任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('choice_count', models.IntegerField(default=0, verbose_name='选择题数量')),
                ('fill_count', models.IntegerField(default=0, verbose_name='填空题数量')),
                ('judge_count', models.IntegerField(default=0, verbose_name='判断题数量')),
                ('short_count', models.IntegerField(default=0, verbose_name='简答题数量')),
                ('calc_count', models.IntegerField(default=0, verbose_name='计算题数量')),
                ('draw_count', models.IntegerField(default=0, verbose_name='画图题数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI智能试卷',
                'verbose_name_plural': 'AI智能试卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='参考年份')),
                ('difficulty', models.CharField(choices=[('易', '易'), ('中', '中'), ('难', '难')], max_length=2, verbose_name='难度')),
                ('knowledge_point', models.CharField(max_length=200, verbose_name='知识点')),
                ('content', models.TextField(help_text='支持 Markdown + LaTeX 公式', verbose_name='AI改写题干')),
                ('options', models.JSONField(blank=True, help_text='选择题必填，JSON 对象格式，如 {"A": "内容", "B": "内容"}', null=True, verbose_name='选项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('original_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaoyan_app.question', verbose_name='溯源真题')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.questiontype', verbose_name='题型')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.school', verbose_name='参考学校')),
            ],
            options={
                'verbose_name': 'AI练习题',
                'verbose_name_plural': 'AI练习题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='题目顺序')),
                ('user_answer', models.TextField(blank=True, null=True, verbose_name='用户答题记录')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_test.aiexam', verbose_name='AI试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_test.aigeneratedquestion', verbose_name='AI题目')),
            ],
            options={
                'verbose_name': 'AI试卷题目明细',
                'verbose_name_plural': 'AI试卷题目明细',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
    ]
