# Generated by Django 6.0.3 on 2026-03-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='选择题填A/B/C/D，判断题填对/错，填空题填标准答案，主观题留空', null=True, verbose_name='正确答案'),
        ),
    ]
