# Generated by Django 6.0.3 on 2026-03-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_test', '0002_aigeneratedquestion_correct_answer'),
        ('kaoyan_app', '0005_subject_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexam',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kaoyan_app.subject', verbose_name='专业课'),
        ),
    ]
