# Generated by Django 6.0.3 on 2026-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_test', '0004_alter_aiexam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='AI 生成的解题思路与简要解析', null=True, verbose_name='简要解析'),
        ),
    ]
