# Generated by Django 6.0.3 on 2026-03-27 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_test', '0005_aigeneratedquestion_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPracticeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('preview', '预览中'), ('taking', '作答中'), ('submitted', '已提交')], default='preview', max_length=10, verbose_name='状态')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='作答时长(秒)')),
                ('score', models.IntegerField(default=0, verbose_name='客观题得分')),
                ('total_objective_score', models.IntegerField(default=0, verbose_name='客观题总分')),
                ('choice_count', models.IntegerField(default=0, verbose_name='选择题数量')),
                ('fill_count', models.IntegerField(default=0, verbose_name='填空题数量')),
                ('judge_count', models.IntegerField(default=0, verbose_name='判断题数量')),
                ('short_count', models.IntegerField(default=0, verbose_name='简答题数量')),
                ('calc_count', models.IntegerField(default=0, verbose_name='计算题数量')),
                ('draw_count', models.IntegerField(default=0, verbose_name='画图题数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI题库练习卷',
                'verbose_name_plural': 'AI题库练习卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPracticeExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='题目顺序')),
                ('user_answer', models.TextField(blank=True, null=True, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_test.aipracticeexam', verbose_name='AI练习卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_test.aigeneratedquestion', verbose_name='AI题目')),
            ],
            options={
                'verbose_name': 'AI练习卷题目明细',
                'verbose_name_plural': 'AI练习卷题目明细',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AIWrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_count', models.IntegerField(default=1, verbose_name='错误次数')),
                ('last_wrong_at', models.DateTimeField(auto_now=True, verbose_name='最近错误时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_test.aigeneratedquestion', verbose_name='AI题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI错题',
                'verbose_name_plural': 'AI错题本',
                'ordering': ['-last_wrong_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
