# Generated by Django 6.0.3 on 2026-03-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_test', '0006_aipracticeexam_aipracticeexamquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexam',
            name='duration_seconds',
            field=models.IntegerField(default=0, verbose_name='作答时长(秒)'),
        ),
        migrations.AddField(
            model_name='aiexam',
            name='score',
            field=models.IntegerField(default=0, verbose_name='客观题得分'),
        ),
        migrations.AddField(
            model_name='aiexam',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始作答时间'),
        ),
        migrations.AddField(
            model_name='aiexam',
            name='total_objective_score',
            field=models.IntegerField(default=0, verbose_name='客观题总分'),
        ),
        migrations.AlterField(
            model_name='aiexam',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成完成时间'),
        ),
        migrations.AlterField(
            model_name='aiexam',
            name='status',
            field=models.CharField(choices=[('pending', '生成中'), ('completed', '待练习'), ('taking', '作答中'), ('submitted', '已提交')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
