# Generated by Django 6.0.3 on 2026-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='question_source',
            field=models.CharField(choices=[('kaoyan', '真题'), ('ai', 'AI题')], default='kaoyan', max_length=10, verbose_name='题目来源'),
        ),
    ]
