# Generated by Django 6.0.3 on 2026-03-29 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_question_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('like', '点赞'), ('reply', '回复'), ('report_accepted', '纠错采纳'), ('report_rejected', '纠错驳回'), ('report_new', '新纠错')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(verbose_name='题目ID')),
                ('question_source', models.CharField(choices=[('kaoyan', '真题'), ('ai', 'AI题')], default='kaoyan', max_length=10, verbose_name='题目来源')),
                ('description', models.TextField(verbose_name='纠错描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/', verbose_name='手写过程图片')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已采纳'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注/驳回原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
            ],
            options={
                'verbose_name': '题目纠错',
                'verbose_name_plural': '题目纠错',
                'ordering': ['-created_at'],
            },
        ),
    ]
