# Generated by Django 6.0.3 on 2026-03-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_notification_noti_type_questionreport'),
        ('kaoyan_app', '0006_alter_question_subject'),
        ('res_center', '0002_alter_resourcecategory_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('like', '点赞'), ('reply', '回复'), ('report_accepted', '纠错采纳'), ('report_rejected', '纠错驳回'), ('report_new', '新纠错'), ('resource_accepted', '资源投稿采纳'), ('resource_rejected', '资源投稿驳回'), ('resource_new', '新资源投稿')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='ResourceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='resource_submissions/%Y%m/', verbose_name='封面图片')),
                ('description', models.TextField(verbose_name='简介')),
                ('link', models.URLField(verbose_name='资源链接')),
                ('price', models.PositiveIntegerField(default=0, help_text='0 表示免费', verbose_name='价格（点数）')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已采纳'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注/驳回原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='res_center.resourcecategory', verbose_name='分类')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resource_submissions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaoyan_app.school', verbose_name='关联学校')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaoyan_app.subject', verbose_name='关联专业课')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_submissions', to=settings.AUTH_USER_MODEL, verbose_name='投稿人')),
            ],
            options={
                'verbose_name': '资源投稿',
                'verbose_name_plural': '资源投稿',
                'ordering': ['-created_at'],
            },
        ),
    ]
