# Generated by Django 6.0.3 on 2026-03-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP开通时间'),
        ),
    ]
