# Generated by Django 6.0.3 on 2026-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_vip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='验证令牌'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
    ]
