# Generated by Django 6.0.3 on 2026-03-28 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email_token_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='验证令牌')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password_hash', models.CharField(max_length=128, verbose_name='密码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
            ],
            options={
                'verbose_name': '待激活注册',
                'verbose_name_plural': '待激活注册',
            },
        ),
    ]
