# Generated by Django 6.0.3 on 2026-03-29 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='站内点数'),
        ),
        migrations.CreateModel(
            name='CoinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='正数为增加，负数为扣除', verbose_name='变动数量')),
                ('reason', models.CharField(choices=[('daily_checkin', '每日打卡'), ('admin_adjust', '管理员调整'), ('reward', '系统奖励'), ('consume', '消费扣除'), ('other', '其他')], default='other', max_length=20, verbose_name='变动原因')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点数记录',
                'verbose_name_plural': '点数记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
