# Generated by Django 6.0.3 on 2026-03-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoyan_app', '0006_alter_question_subject'),
        ('user', '0006_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kaoyan_session',
            field=models.IntegerField(blank=True, choices=[(27, '第27届考研（2026年12月）'), (28, '第28届考研（2027年12月）'), (29, '第29届考研（2028年12月）'), (30, '第30届考研（2029年12月）')], null=True, verbose_name='考研届次'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='学习开始日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaoyan_app.school', verbose_name='目标院校'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='成就代码')),
                ('name', models.CharField(max_length=30, verbose_name='成就名称')),
                ('icon', models.CharField(max_length=30, verbose_name='图标')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'code')},
            },
        ),
    ]
