# Generated by Django 6.0.3 on 2026-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_kaoyan_session_user_study_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='code',
            field=models.CharField(max_length=30, verbose_name='成就代码'),
        ),
    ]
