# Generated by Django 6.0.3 on 2026-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_achievement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrecord',
            name='reason',
            field=models.CharField(choices=[('daily_checkin', '每日打卡'), ('wheel_spin', '幸运转盘'), ('admin_adjust', '管理员调整'), ('reward', '系统奖励'), ('consume', '消费扣除'), ('other', '其他')], default='other', max_length=20, verbose_name='变动原因'),
        ),
    ]
