# Generated by Django 6.0.3 on 2026-03-29 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaoyan_app', '0006_alter_question_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('icon', models.CharField(default='fa-folder', help_text='Font Awesome 图标类名，如 fa-video、fa-file-pdf', max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序（越小越靠前）')),
            ],
            options={
                'verbose_name': '资源分类',
                'verbose_name_plural': '资源分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='resource_covers/%Y%m/', verbose_name='封面图片')),
                ('description', models.TextField(help_text='支持 Markdown + LaTeX 公式', verbose_name='简介')),
                ('link', models.URLField(verbose_name='资源链接')),
                ('price', models.PositiveIntegerField(default=0, help_text='0 表示免费', verbose_name='价格（点数）')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载/获取次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaoyan_app.school', verbose_name='关联学校')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kaoyan_app.subject', verbose_name='关联专业课')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='res_center.resourcecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_paid', models.PositiveIntegerField(verbose_name='支付点数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='res_center.resource', verbose_name='资源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_purchases', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资源购买记录',
                'verbose_name_plural': '资源购买记录',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
