# Generated by Django 6.0.3 on 2026-03-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='icon',
            field=models.CharField(choices=[('fa-folder', '📁 文件夹'), ('fa-file', '📄 文件'), ('fa-file-pdf', '📕 PDF'), ('fa-file-lines', '📝 文档'), ('fa-file-image', '🖼️ 图片'), ('fa-file-zipper', '📦 压缩包'), ('fa-video', '🎬 视频'), ('fa-headphones', '🎧 音频'), ('fa-book', '📖 书籍'), ('fa-book-open', '📕 教材'), ('fa-graduation-cap', '🎓 学位'), ('fa-pen-fancy', '✏️ 笔记'), ('fa-brain', '🧠 知识点'), ('fa-lightbulb', '💡 技巧'), ('fa-flask', '🧪 实验'), ('fa-calculator', '🧮 计算'), ('fa-code', '💻 代码'), ('fa-database', '🗄️ 数据'), ('fa-chart-bar', '📊 图表'), ('fa-clipboard-list', '📋 清单'), ('fa-star', '⭐ 精选'), ('fa-trophy', '🏆 真题'), ('fa-shield-halved', '🛡️ 答案'), ('fa-puzzle-piece', '🧩 练习'), ('fa-fire', '🔥 热门'), ('fa-gem', '💎 稀有'), ('fa-download', '⬇️ 下载'), ('fa-link', '🔗 链接'), ('fa-cloud-arrow-up', '☁️ 云资源'), ('fa-newspaper', '📰 资讯')], default='fa-folder', max_length=50, verbose_name='图标'),
        ),
    ]
